version: '3.9'
services:
  postgres:
    env_file:
      - .env
    image: postgres:latest
    container_name: gRPC-Interaction
    restart: always
    ports:
      - "49051:5432"


# docker compose up -d