GRPC:
  host: localhost
  port: 5001

database:
  host: postgres
  username: auth_user
  password: password
  db-url: localhost
  db-name: auth_db
  port: 49051

token:
  secret-password-salt: salt
  secret-key-here: secret_password
  expiration: 15m