GRPC:
  host: 127.0.0.1
  port: 50051

database:
  DB_CONNECTION_STRING: postgres://zatrasz:postgrespw@localhost:49051/Interaction-gRPC?sslmode=disable

  host: postgres
  username: zatrasz
  password: postgrespw
  db-url: localhost
  db-name: Interaction-gRPC
  port: 49051

token:
  secret-password-salt: salt
  secret-key-here: secret_password
  expiration: 15m