GRPC:
  host: localhost
  port: 5003

database:
  host: postgres
  username: user_info_user
  password: password
  db-url: localhost
  db-name: user_info_db
  port: 49053

token:
  secret-key-here: secret_password